# fly.toml app configuration file generated for the-plug-swizzzler on 2025-09-29T04:57:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-plug-swizzzler'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
